title: scheng
description: Simple documentation site using Just the Docs.
remote_theme: just-the-docs/just-the-docs

url: "https://schwwaaa.github.io"
baseurl: "/scheng-docs"

just_the_docs:
  search_enabled: true
  nav_sort: case_insensitive

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
